project:
  type: book

book:
  title: "Lab notebook"
  subtitle: "The role of climate and competition on tree range distribution: a multi-scale approach from individuals to metapopulation dynamics"
  author:
    - name: Willian Vieira
      orcid: 0000-0003-0283-4570
    - name: Andrew MacDonald
      orcid: 0000-0003-1162-169X
    - name: Amaël Le Squin
      orcid: 0000-0003-3516-4155
    - name: Robert L. Bradley
    - name: Dominique Gravel
      orcid: 0000-0002-4498-7076

  search: true
  repo-url: "https://github.com/willvieira/book_forest-demography-IPM/"
  repo-actions: [issue]
  # cover-image: cover.png
  chapters:
    - index.qmd
    - introduction.qmd
    - db.qmd
    - part: Demographic models
      chapters:
      - model_description.qmd
      - covariates_description.qmd
      - model_fit.qmd
      - model_comparison.qmd
      - parameters_descr.qmd
    - part: Demographic model evaluation
      chapters:
      - pars_intercept.qmd
      - pars_randomEffect.qmd
      - pars_competition.qmd
      - pars_climate.qmd
      - pars_effectSize.qmd
      - pars_condEffect.qmd
    - part: Using demographic models to infer population level performance
      chapters:
      - ipm_description.qmd
      - guide_IPM.qmd
      - sens_analysis.qmd
      - conditional_lambda.qmd
      - marginal_lambda.qmd
      - extinction_risk.qmd
    - references.qmd

bibliography: references.bib

website:
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    theme: [cosmo, mytheme.scss]
  # pdf:
  #   documentclass: scrreprt
  #   geometry:
  #     - top=20mm
  #     - left=25mm
  #     - right=15mm
  #     - bottom=20mm
  # docx:
  #   toc: false

number-depth: 1