project:
  type: book

book:
  title: "Supplementary material"
  subtitle: "Competition and climate effect on the dynamics of North American forest trees - from individuals to population"
  author:
    - name: Willian Vieira
      orcid: 0000-0003-0283-4570

  search: true
  repo-url: "https://github.com/willvieira/ms_forest-demography-IPM/"
  repo-actions: [issue]
  # cover-image: cover.png
  chapters:
    - index.qmd
    - db.qmd
    - part: Demographic models
      chapters:
      - pars_intercept.qmd
      - pars_randomEffect.qmd
      - pars_size.qmd
      - pars_competition.qmd
      - pars_climate.qmd
      - pars_effectSize.qmd
      - pars_condEffect.qmd
      # - descript_demoModels.qmd
    - part: Coexistence
      chapters:
      - coex.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    keep-md: true
  pdf:
    documentclass: scrreprt
  docx:
    toc: false

number-depth: 1