# Integral Projection Model {#sec-ipm_description}

The Integral Projection Model (IPM) is a category of mathematical tools used to improve our understanding of population dynamics.
It distinguishes itself from other traditional population models by assuming that the population is structured based on a continuous trait [@Easterling2000].
Specifically, an IPM consists of a set of functions that predicts the transition of a distribution of individual traits from time $t$ to time $t+1$:

$$
n(z', t + 1) = \int_{L}^{U} \, k(z', z, \theta)\, n(z, t)\, \mathrm{d}z
$$

In our case, the continuous trait $z$ at time $t$ and $z'$ at time $t+1$ represent the diameter at breast height (DBH), and $n(z, t)$ characterizes the continuous DBH distribution for a population.
The projection probability of the population distribution size from $n(z, t)$ to $n(z', t+1)$ is governed by the kernel $K$ and the species-specific parameters $\theta$. The kernel $K$ s composed of the three sub-models we described above:

$$
k(z', z, \theta) = [Growth(z', z, \theta) \times Survival(z, \theta)] + Recruitment(z, \theta)
$$


## Numerical implementation

- We use the mid point rule [@Ellner2016]
- bins ($h$) with size ranging 0.1 - 1 cm are appropriated to obtain reliable outputs [@zuidema2010integral] -> we use a bin of 0.1 to avoid overestimating the projection. Furthermore, we do not attempt to use the absolute value of the species, but to compare the relative population growth between species and covariates.

## IPM outputs

- $\lambda$
- Population size at equilibrium  ($N^*$) -> carrying capacity
- Extinction probability from the $\lambda$ or $N^*$ uncertainity
